### PR TITLE
Fixed the new updated parameters definitions

### PR DESCRIPTION
**Pull request by csolje**
--timepos -> --time-pos
--datepos -> --date-pos
--datestr -> --date-str
--insidecolor -> --inside-color
--ringcolor -> --ring-color
--ringvercolor -> --ringver-color
--keyhlcolor -> --keyhl-color
--bshlcolor -> --bshl-color
--separatorcolor -> --separator-color
--insidevercolor -> --insidever-color
--insidewrongcolor -> --insidewrong-color
--ringvercolor -> --ringver-color
--ringwrongcolor -> --ringwrong-color
--indpos -> --ind-pos
--veriftext -> --verif-text
--wrongtext -> --wrong-text
--verifcolor -> --verif-color
--timecolor -> --time-color
--datecolor -> --date-color
--noinputtext -> --noinput-text

### CODE REVIEW

**Comment by oakszyjrnrdy** [comment]
Thanks! Could you change `betterlockscreen_rapid.conf` to make those variables consistent?

**Comment by csolje** [comment]
Just commited it for you

**Comment by oakszyjrnrdy** [comment]
When you change names of variables in `betterlockscreen_rapid.conf`, you need to change their names in `betterlockscreen_rapid` at the same time.
Those variables are actually shell variables, which contain only letters, numbers or the underscore character`_`, but not `-`. Using `_` in the variable names may be a good idea.

That means you need to the following things if you want:
1. change affected names of variables in `betterlockscreen_rapid.conf`, e.g. `inside-color -> inside_color`
2. change their names in `betterlockscreen_rapid` according to `betterlockscreen_rapid.conf`, e.g. `--inside-color "$insidecolor" -> --inside-color "$inside_color"`

Also, it's fine for you to change just the flag names and remain variable names unchanged in this PR. In that case, I will change those variables later.

**Comment by csolje** [comment]
No worries I will change that later sorry I forgot about that.

**Review by jian-lin — CHANGES_REQUESTED** [review]
You forgot to change `$separatorcolor` in  `--separator-color "$separatorcolor"`

**Comment by oakszyjrnrdy** [comment]
Thanks for you work!
In order to fix this problem earlier for users, I merged (#3).
Since it is fixed, I'll close this PR.

**Pull request closed without merging**
